trigger:
- main
pool:
  name: default
steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
  env:
    VERACODE_API_KEY: $(VERACODE_API_KEY)
    script: |
      # Write your commands here
      VERACODE_WRAPPER_VERSION=$(curl -sS "https://search.maven.org/solrsearch/select?q=g:%22com.veracode.vosp.api.wrappers%22&rows=20&wt=json" | jq -r '.response.docs[0].latestVersion') && curl -sS -o veracode-wrapper.jar "https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/${VERACODE_WRAPPER_VERSION}/vosp-api-wrappers-java-${VERACODE_WRAPPER_VERSION}.jar"
      java -jar veracode-wrapper.jar -vid $VERACODE_API_ID -vkey $VERACODE_API_KEY -action PromoteSandbox -buildid 28649112
#      java -jar veracode-wrapper.jar -credprofile default -action PromoteSandbox -buildid 28649112

